New log file opened at Mon Apr 25 09:33:44 ICT 2016 by 18522@giangbb-comp
Taking next connection to: 39424
New client attempting to connect on port: 49528-39424
  Address = /127.0.1.1:39424
This client on port 49528 has uuid ea4ce929-857a-4b1f-ab45-ea78b30e26c0 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: play-fork-run-ea4ce929-857a-4b1f-ab45-ea78b30e26c0
Taking next connection to: 39424
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 39424
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 39424
New client attempting to connect on port: 49932-39424
  Address = /127.0.1.1:39424
Handshake exception on socket: 49932
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 39424
New client attempting to connect on port: 49934-39424
  Address = /127.0.1.1:39424
This client on port 49934 has uuid c3b6d41d-66c1-4ce3-a31f-3bc393367abc configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: play-fork-run-c3b6d41d-66c1-4ce3-a31f-3bc393367abc
Taking next connection to: 39424
New client attempting to connect on port: 49972-39424
  Address = /127.0.1.1:39424
Handshake exception on socket: 49972
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 39424
New client attempting to connect on port: 49974-39424
  Address = /127.0.1.1:39424
This client on port 49974 has uuid cd3092d2-7e68-4d9e-9808-f5cec60d258b configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: play-fork-run-cd3092d2-7e68-4d9e-9808-f5cec60d258b
Taking next connection to: 39424
